## WARNING This file is automatically generated. Do not edit it manually. ##
interface InternalGBP
    exposes [
        GraphemeBreakProperty,
    ]
    imports []

GraphemeBreakProperty : [
    CR,
    LF, 
    Control,
    Extend,
    ZWL,
    RI,
    Prepend,
    SpacingMark,
    L,
    V,
    T,
    LV,
    LVT,
    Other,
]

expect 1 == 1