name: Generate docs

on:
  # Run when a release is published
  release:
    types:
      - published

jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Downloading latest roc nightly
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz

      - name: prep nightly tar for use
        run: |
          mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz
          tar -xzf roc_nightly.tar.gz
          rm roc_nightly.tar.gz
          mv roc_nightly* roc_nightly

      - run: ./roc_nightly/roc version

      - name: Generate docs
        run: ./roc_nightly/roc docs package/main.roc
      
      - name: Fix absolute paths
        run: |
          find generated-docs/ -type f -name '*.html' -exec sed -i "s/\(href\|src\)=\"\//\1=\"\/${{ github.event.repository.name }}\//g" {} +
      
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: generated-docs

      - name: Deploy docs
        uses: actions/deploy-pages@v4