on: 
    pull_request:
    workflow_dispatch:
  
  # this cancels workflows currently in progress if you start a new one
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
jobs:  
    test-examples-nix:
      runs-on: [ubuntu-22.04]
      steps:
        - uses: actions/checkout@v3
      
        # install nix
        - uses: cachix/install-nix-action@v23
          with:
            nix_path: nixpkgs=channel:nixos-unstable
  
        # Run all tests 
        - name: Run all tests
          run: nix develop -c sh -c 'export ROC=roc && ./ci/all_tests.sh'