on: 
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-examples-ubuntu:
    runs-on: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
    
      - name: Downloading latest roc nightly
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz

      - name: prep nightly tar for use
        run: |
          mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz
          tar -xzf roc_nightly.tar.gz
          rm roc_nightly.tar.gz
          mv roc_nightly* roc_nightly

      - run: ./roc_nightly/roc version

      # expect for testing
      - run: sudo apt install -y expect

      - run: expect -v

      # Run all tests 
      - run: ROC=./roc_nightly/roc ./ci/all_tests.sh